# Generated by Django 4.2.7 on 2023-12-21 09:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import perevalinfo.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=34.3, help_text='широта в градусах', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта')),
                ('longitude', models.FloatField(default=61.8, help_text='долгота в градусах', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота')),
                ('height', models.IntegerField(default=0, help_text='высота в метрах над уровнем моря', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8848)], verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=10, null=True, verbose_name='Зима')),
                ('spring', models.CharField(blank=True, max_length=10, null=True, verbose_name='Весна')),
                ('summer', models.CharField(blank=True, max_length=10, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=10, null=True, verbose_name='Осень')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255)),
                ('connect', models.CharField(default=' ', max_length=1)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('status', models.CharField(choices=[('NE', 'Новый'), ('PE', 'В работе'), ('AC', 'Принято'), ('RE', 'Не принято')], default='NE', max_length=2, verbose_name='Состояние')),
                ('coord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coord', to='perevalinfo.coords', verbose_name='Координаты')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='perevalinfo.difficultylevel', verbose_name='Сложность')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pereval', to='perevalinfo.perevaladded', verbose_name='Доб. перевалы')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=perevalinfo.services.post_media_directory_path, verbose_name='Фото')),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='perevalinfo.perevaladded', verbose_name='Фотографии')),
            ],
        ),
    ]
