# Generated by Django 4.2.7 on 2023-12-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perevalinfo', '0002_rename_beautytitle_perevaladded_beauty_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='coord_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pereval_coord', to='perevalinfo.coords', verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pereval_level', to='perevalinfo.difficultylevel', verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pereval_user', to='perevalinfo.users', verbose_name='Автор'),
        ),
    ]
