# Generated by Django 4.2.7 on 2023-12-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalinfo', '0003_alter_perevaladded_coord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.CharField(default='', max_length=1),
        ),
    ]
