# Generated by Django 4.2.7 on 2023-12-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalinfo', '0004_alter_perevaladded_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('NW', 'Новый'), ('PN', 'В работе'), ('AC', 'Принято'), ('RJ', 'Не принято')], default='W', max_length=2, verbose_name='Состояние'),
        ),
    ]
