# Generated by Django 4.2.7 on 2023-12-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perevalinfo', '0005_alter_perevaladded_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('NW', 'Новый'), ('PN', 'В работе'), ('AC', 'Принято'), ('RJ', 'Не принято')], default='Новый', max_length=10, verbose_name='Состояние'),
        ),
    ]
